[package]
name = "lexa-prompt-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
lexa-syn = { git = "https://github.com/PhiSyX/lexa-syn.git" }
syn = { version = "^2.0", features = ["full"] }
